######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 11 15:31:27 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
# Input
HEADERS += rss_entry.h rss_http_engine.h rss_list_model.h
SOURCES += rss_entry.cpp \
           rss_http_engine.cpp \
           rss_list_model.cpp \
           rss_tag.cpp \
           test.cpp
